baseURL = "https://viridiantechs.com/"
relativeURLs = true
canonifyURLs  = true
publishDir    = "public"
ignoreFiles = ["\\.(jpg|png|gif|svg|scss)$"]

[server]
  # Only watch the folders you actually edit
  watch = ["content", "layouts", "data"]
